### ISSUE TITLE
Null pointer exception on recycler adapter 

### ISSUE THREAD

**Issue by varshneyankit** [varshneyankit/OMDb_Client#1]
File MovieListFragments.java 
 line 88,31,65

 java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View androidx.recyclerview.widget.RecyclerView.findViewById(int)' on a null object reference
        at com.example.omdb_clientapp.ui.MovieListFragment.updateAdapterData(MovieListFragment.java:88)
        at com.example.omdb_clientapp.ui.MovieListFragment.access$000(MovieListFragment.java:31)
        at com.example.omdb_clientapp.ui.MovieListFragment$1.onResponse(MovieListFragment.java:65)
        at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.lambda$onResponse$0$DefaultCallAdapterFactory$ExecutorCallbackCall$1(DefaultCallAdapterFactory.java:82)
        at retrofit2.-$$Lambda$DefaultCallAdapterFactory$ExecutorCallbackCall$1$3wC8FyV4pyjrzrYL5U0mlYiviZw.run(Unknown Source:6)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by singaltanmay** [comment]
Title pehle vaala theek tha. Extra details in issue description

**Comment by singaltanmay** [comment]
Line  88,31,65?

**Comment by singaltanmay** [comment]
Title = Null pointer exception on recycler adapter

**Comment by singaltanmay** [comment]
`recyclerView = recyclerView.findViewById(R.id.fragment_movie_list_recycler_view);`
How can you access `recyclerView` while assigning it a value for the first time?

**Comment by varshneyankit** [comment]
> `recyclerView = recyclerView.findViewById(R.id.fragment_movie_list_recycler_view);`
> How can you access `recyclerView` while assigning it a value for the first time?

Declared recycler adapter at line 32

**Comment by singaltanmay** [comment]
Also, `updateAdapterData()` is used to **update** data in the adapter so you shouldn't initalize the recycler every time data has to be updated.

**Comment by singaltanmay** [comment]
https://github.com/varshneyankit/OMDb_Client/blob/61d953cb1f2d3cfd6c59dff059448b49087eaa9b/app/src/main/java/com/example/omdb_clientapp/ui/MovieListFragment.java#L32 Here recyclerView has been declared but not assigned

**Comment by varshneyankit** [comment]
> `recyclerView = recyclerView.findViewById(R.id.fragment_movie_list_recycler_view);`
> How can you access `recyclerView` while assigning it a value for the first time?

Declared recycler adapter at line 32
